# This .yml file uses our shared vue-component-template file to define anchors and stages
include:
  - project: "devops/shared_yaml"
    ref: master
    file: "bits-module-template.yml"

build-rc:
  extends: .build-rc-template

build-release:
  extends: .build-release-template

build-master:
  extends: .build-master-template

build-branch:
  extends: .build-branch-template
